# .github/workflows/discord-notify.yml
name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send pretty Discord embed
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO:   ${{ github.repository }}
          REF:    ${{ github.ref_name }}
          ACTOR:  ${{ github.actor }}
          SHA:    ${{ github.sha }}
          MSG:    ${{ github.event.head_commit.message }}
          URL:    ${{ github.event.head_commit.url }}
        run: |
          # build embed JSON
          payload=$(
            jq -n \
              --arg title   "📦 New push to $REPO" \
              --arg url     "$URL" \
              --arg desc    "$MSG" \
              --arg branch  "$REF" \
              --arg actor   "$ACTOR" \
              --arg ts      "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
              '{
                embeds: [
                  {
                    title:      $title,
                    url:        $url,
                    description:$desc,
                    color:      3066993,
                    fields: [
                      { name: "Branch", value: $branch, inline: true },
                      { name: "Author", value: $actor,  inline: true }
                    ],
                    timestamp:  $ts
                  }
                ]
              }'
          )

          # POST to Discord
          curl -X POST "$WEBHOOK" \
               -H "Content-Type: application/json" \
               -d "$payload"
